"""Synthetic plates to try things on, and Cell Painting Gallery accessions to check them against."""

from mantispy.ds._blobs import blobs
from mantispy.ds._datasets import (
    JUMP_LITE_MODELS,
    agnp,
    amish,
    bbbc021,
    chroma,
    jump_cells,
    jump_crispr,
    jump_export,
    jump_lite,
    jump_lite_targets,
    jump_plate,
    jump_target2,
    luad,
    miami,
    neuropainting,
    oasis_pilot,
    pki,
    pooled_rare,
    rohban,
)
from mantispy.ds._synthetic import DEFAULT_CHANNELS, synthetic_plate

__all__ = [
    "DEFAULT_CHANNELS",
    "agnp",
    "amish",
    "bbbc021",
    "blobs",
    "chroma",
    "jump_cells",
    "JUMP_LITE_MODELS",
    "jump_crispr",
    "jump_lite",
    "jump_lite_targets",
    "jump_export",
    "jump_plate",
    "jump_target2",
    "luad",
    "miami",
    "neuropainting",
    "oasis_pilot",
    "pki",
    "pooled_rare",
    "rohban",
    "synthetic_plate",
]
